#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright 2019 <company_name>
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
################# WARNING ####################
##############################################
###
### This file is auto generated by the resource
###   module builder playbook.
###
### Do not edit this file manually.
###
### Changes to this file will be over written
###   by the resource module builder.
###
### Changes should be made in the model used to
###   generate this file or in the resource module
###   builder template.
###
##############################################
##############################################
##############################################
"""
The arg spec for the networkos_interfaces module
"""

class InterfacesArgs(object): #pylint: disable=R0903
    """The arg spec for the networkos_interfaces module
    """

    def __init__(self, **kwargs):
        pass

    argument_spec = {u'state': {'default': u'merged', 'required': False, 'type': u'str', 'choices': [u'merged', u'replaced', u'overridden', u'deleted']}, u'config': {'options': {u'some_int': {'required': False, 'type': u'int', 'version_added': u'1.1'}, u'some_string': {'default': u'choice_a', 'required': True, 'type': u'str', 'choices': [u'choice_a', u'choice_b', u'choice_c']}, u'some_dict': {'options': {u'property_01': {'required': False, 'type': u'str'}, u'property_02': {'default': u'choice_a', 'required': False, 'type': u'str', 'choices': [u'choice_a', u'choice_b', u'choice_c']}}}, u'some_bool': {'required': False, 'type': u'bool'}, u'some_list_of_dicts': {'options': {u'property_01': {'required': False, 'type': u'str'}, u'property_02': {'default': u'choice_a', 'required': False, 'type': u'str', 'choices': [u'choice_a', u'choice_b', u'choice_c']}}}}}} #pylint: disable=C0301
